services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
